### ISSUE TITLE
DDOS vulnerability

### ISSUE THREAD

**Issue by serialgamr** [serialgamr/Rest-server#1]

**Comment by Serial-DeV** [comment]
Hey, what's the issue exactly. I might be able to help you (or not!)

**Comment by serialgamr** [comment]
Actually, I would like to find a way to avoid to be spammed. Maybe by putting a connexion limiter or sth like that

**Comment by Serial-DeV** [comment]
Mhhh, I think I can help you

**Comment by serialgamr** [comment]
Niiiice

**Comment by serialgamr** [comment]
Perfect, thanks
